### ISSUE TITLE
ImportError: No module named mosaic

### ISSUE THREAD

**Issue by VeraWulol** [lsst/meas_mosaic#16]
As I scons, the error is reported as:
```
running tests/testCameraGeomShim.py... failed
Failed test output:
tests/testCameraGeomShim.py

Traceback (most recent call last):
  File "tests/testCameraGeomShim.py", line 26, in <module>
    import lsst.meas.mosaic as measMosaic
ImportError: No module named mosaic
The following tests failed:
/home/verawu/my_packages/meas_mosaic/tests/.tests/testCameraGeomShim.py.failed
1 tests failed
scons: *** [checkTestStatus] Error 1
scons: building terminated because of errors.
```
which, as I checked, mosaic do exist inside the lsst/meas

**Comment by jdswinbank** [comment]
Thanks for the report!

Can you provide a bit more information about how you've reached this point? How have you installed the rest of the LSST stack? Did you just type `scons`, or did you provide it with any other arguments?

**Comment by VeraWulol** [comment]
Dear Mr Swinbank,
The error.txt contains the error message as I typed "scons" only. I did not provide any argument nor option to it.
The list.txt contains the output of "eups list". We have installed the LSST stack with lsstsw and lsst-build. The LSST installation should work fine as it has been running for all other commands for some time.

Thank you,VeraWu 

    John Swinbank <notifications@github.com> 於 2017年07月14日 (週五) 12:47 PM 寫道﹕
 

 Thanks for the report!Can you provide a bit more information about how you've reached this point? How have you installed the rest of the LSST stack? Did you just type scons, or did you provide it with any other arguments?—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   
scons: Reading SConscript files ...
EUPS integration: enabled
Checking who built the CC compiler...(cached) gcc=4.8.2
CC is gcc version 4.8.2
Checking for C++11 support
Checking whether the C++ compiler works... (cached) yes
C++11 supported with '-std=c++11'
Setting up environment to build package 'meas_mosaic'.
Could not find EUPS product dir for 'meas_mosaic'; using /home/verawu/my_packages/meas_mosaic.
scons: done reading SConscript files.
scons: Building targets ...
scons: `lib' is up to date.
scons: `python' is up to date.
running tests/testCameraGeomShim.py... failed
scons: `shebang' is up to date.
Failed test output:
tests/testCameraGeomShim.py

Traceback (most recent call last):
  File "tests/testCameraGeomShim.py", line 26, in <module>
    import lsst.meas.mosaic as measMosaic
ImportError: No module named mosaic
The following tests failed:
/home/verawu/my_packages/meas_mosaic/tests/.tests/testCameraGeomShim.py.failed
1 tests failed
scons: *** [checkTestStatus] Error 1
scons: building terminated because of errors.

activemqcpp           3.9.0.lsst2+3 	b2896 b2895
afw                   12.1+6     	b2896
afw                   13.0-28-g978e321+1 	current b2894 setup
afwdata               12.1+1     	b2896 b2895
afwdata               13.0-1-g1546c47+2 	current b2894 setup
apr                   1.5.2      	current b2896 b2894 b2895 setup
apr_util              1.5.4      	current b2896 b2894 b2895 setup
astrometry_net        0.67.123ff3e.lsst1+1 	current b2896 b2894 b2895 setup
astrometry_net_data   10.0+86    	b2896 b2895
astrometry_net_data   10.0+92    	current b2894
astrometry_net_data   ps1_pv3_3pi_20170110-and 
astrometry_net_data   tag:verawu 	verawu setup
astropy               0.0.1.lsst2+2 	current b2896 b2894 b2895 setup
astshim               master-gb637561bb9 	current b2894 setup
base                  12.1+2     	b2896 b2895
base                  13.0-4-g0bde1de 	current b2894 setup
boost                 1.60.lsst1+1 	current b2896 b2894 b2895 setup
cat                   12.1+19    	b2896
cfitsio               3360.lsst4 	current b2896 b2894 b2895 setup
ci_hsc                LOCAL:/home/verawu/ci_hsc 	setup
coadd_chisquared      12.1+5     	b2896
coadd_chisquared      13.0-2-ga4f5e85+2 	current b2894 setup
coadd_utils           12.1+5     	b2896
coadd_utils           13.0-2-gf5c5ced+2 	current b2894 setup
ctrl_events           12.1+23    	b2896 b2895
ctrl_execute          12.1+37    	b2896
ctrl_orca             12.1+3     	b2896
ctrl_platform_gordon  12.1+3     	b2896
ctrl_platform_lsst    12.1+3     	b2896
ctrl_pool             12.1+11    	b2896
ctrl_pool             13.0-2-gb1fa231+3 	current b2894 setup
ctrl_provenance       12.1+39    	b2896
daf_base              12.1+8     	b2896 b2895
daf_base              13.0-1-g174df6e+3 	current b2894 setup
daf_butlerUtils       12.1+10    	b2896
daf_persistence       12.1+10    	b2896
daf_persistence       13.0-6-gf146911 	current b2894 setup
datarel               12.1+12    	b2896
db                    12.1+13    	b2896 b2895
display_ds9           12.1+10    	b2896
display_ds9           13.0-2-g6174d4c+2 	current b2894
doxygen               1.8.5.lsst1 	current b2896 b2894 b2895 setup
eigen                 3.2.5.lsst2 	current b2896 b2894 b2895 setup
esutil                0.6.0+1    	current b2896 b2894 b2895 setup
fftw                  3.3.4.lsst2 	current b2896 b2894 b2895 setup
galsim                1.4.3      	current b2896 b2894 b2895 setup
geom                  12.1+25    	current b2894 setup
geom                  12.1+26    	b2896 b2895
gsl                   1.16.lsst3 	current b2896 b2894 b2895 setup
healpy                1.8.1.lsst2+5 	current b2896 b2894 b2895 setup
ip_diffim             12.1+13    	b2896
ip_diffim             13.0-10-gcc6134a+2 	current b2894 setup
ip_isr                12.1+9     	b2896
ip_isr                13.0-9-g733b75c+2 	current b2894 setup
lmfit                 0.9.3+4    	current b2896 b2894 b2895 setup
log                   12.1+3     	b2896 b2895
log                   13.0-2-g15de9a1+3 	current b2894 setup
log4cxx               0.10.0.lsst7 	current b2896 b2894 b2895 setup
lsst                  12.1+1     	b2896 b2895
lsst_apps             12.1+20    	b2896
lsst_apps             13.0-2-gcc7d151+2 	current b2894
lsst_build            LOCAL:/export/rliu/lsstsw/lsst_build 	setup
lsst_distrib          12.1+74    	b2896
mariadb               10.1.21.lsst1 	b2896 b2895
mariadbclient         10.1.21.lsst1 	current b2896 b2894 b2895 setup
matplotlib            0.0.4      	current b2896 b2894 b2895 setup
meas_algorithms       12.1+8     	b2896
meas_algorithms       13.0-8-g1664ca9+2 	current b2894 setup
meas_astrom           12.1+12    	b2896
meas_astrom           13.0-4-g2013b0d+2 	current b2894 setup
meas_base             12.1+8     	b2896
meas_base             13.0-9-gd0b67f9+2 	current b2894 setup
meas_deblender        12.1+6     	b2896
meas_deblender        13.0-5-g6708b9e+5 	current b2894 setup
meas_extensions_photometryKron 12.1+10    	b2896
meas_extensions_photometryKron 13.0-4-ge460333+2 	current b2894 setup
meas_extensions_psfex 12.1+9     	b2896
meas_extensions_psfex 13.0-3-gbddb874+2 	current b2894 setup
meas_extensions_shapeHSM 12.1+6     	b2896
meas_extensions_shapeHSM 13.0-6-g11b35ca+2 	current b2894 setup
meas_extensions_simpleShape 12.1+11    	b2896
meas_extensions_simpleShape 13.0-5-gaa0a428+2 	current b2894 setup
meas_modelfit         12.1+5     	b2896
meas_modelfit         13.0-7-g0effe82+3 	current b2894 setup
minuit2               5.34.14    	current b2896 b2894 b2895 setup
mpi                   0.0.1+2    	current b2896 b2894 b2895 setup
mpi4py                2.0.0+2    	current b2896 b2894 b2895 setup
mpich                 3.2.lsst1  	current b2896 b2894 b2895 setup
mysqlpython           1.2.3.lsst2+11 	b2896 b2895
ndarray               1.2.0.lsst1+1 	b2896 b2895
ndarray               1.3.0-1-g4a984de+1 	current b2894 setup
numpy                 0.0.3+1    	current b2896 b2894 b2895 setup
obs_base              13.0-13-gdd29b46+1 	current b2894 setup
obs_cfht              12.1+4     	b2896
obs_cfht              13.0-6-g04cb674+2 	current b2894 setup
obs_decam             12.1+4     	b2896
obs_decam             13.0-9-gc3084d4+1 	current b2894 setup
obs_file              tag:current 	current
obs_lsstSim           12.1+5     	b2896
obs_lsstSim           13.0-5-g109809a+2 	current b2894
obs_sdss              12.1+5     	b2896
obs_sdss              13.0-4-g6df16d3+4 	current b2894
obs_subaru            12.1+4     	b2896
obs_subaru            13.0-21-g3792e7d+1 	current b2894 setup
obs_test              12.1+10    	b2896
obs_test              13.0-6-g7b63e3f+2 	current b2894 setup
pex_config            12.1+9     	b2896 b2895
pex_config            13.0-1-g41367f3+3 	current b2894 setup
pex_exceptions        12.1+11    	b2896 b2895
pex_exceptions        13.0-1-g52a7baa+3 	current b2894 setup
pex_logging           12.1+17    	b2896 b2895
pex_policy            12.1+17    	b2896 b2895
pex_policy            13.0-1-g47a359c+3 	current b2894 setup
pipe_base             12.1+8     	b2896
pipe_base             13.0-3-g7fa07e0 	current b2894 setup
pipe_drivers          12.1+7     	b2896
pipe_drivers          13.0-3-gfcfef02+7 	current b2894
pipe_drivers          tag:verawu 	verawu setup
pipe_tasks            12.1+9     	b2896
pipe_tasks            13.0-20-gd86ed56+1 	current b2894 setup
psfex                 12.0+14    	current b2894 setup
psfex                 12.1+1     	b2896 b2895
pybind11              master-g715ff27535 	current b2894 setup
pyfits                3.4.0+7    	current b2896 b2894 b2895 setup
pykg_config           1.3.0+1    	current b2896 b2894 b2895 setup
python                0.0.6      	current b2896 b2894 b2895 setup
python_d2to1          0.2.12.lsst2+1 	current b2896 b2894 b2895 setup
python_future         0.16.0     	current b2896 b2894 b2895 setup
python_mysqlclient    1.3.7.lsst1+8 	current b2896 b2894 b2895
python_psutil         4.1.0+3    	current b2896 b2894 b2895 setup
pyyaml                3.11.lsst1+3 	current b2896 b2894 b2895 setup
scipy                 0.0.1.lsst1+3 	current b2896 b2894 b2895 setup
scisql                0.3.5-1-g0c09214+1 	b2896 b2895
scons                 2.5.0.lsst2+1 	current b2896 b2894 b2895 setup
sconsUtils            12.1+1     	b2896 b2895
sconsUtils            13.0-3-ga4b1818 	current b2894 setup
shapelet              12.1+8     	b2896
shapelet              13.0-3-g20b541e+2 	current b2894 setup
skymap                12.1+6     	b2896
skymap                13.0-2-gf9e84ea+2 	current b2894 setup
skypix                12.1+56    	b2896
skypix                13.0+26    	current b2894 setup
sqlalchemy            1.0.8.lsst3+3 	b2896 b2895
starlink_ast          lsst-dev-gc4be228eb6 	current b2894 setup
stsci_distutils       0.3.7.lsst1+2 	current b2896 b2894 b2895 setup
swig                  3.0.10     	current b2896 b2894 b2895 setup
testdata_cfht         12.1       	b2896 b2895
testdata_cfht         13.0-1-g2bee09e 	current b2894 setup
testdata_decam        12.1       	b2896 b2895
testdata_decam        13.0-2-gdd95a3b 	current b2894 setup
testdata_subaru       12.1       	b2896 b2895
testdata_subaru       13.0-1-gf61fcd2 	current b2894 setup
tmv                   0.73+5     	current b2896 b2894 b2895 setup
utils                 12.1+6     	b2896 b2895
utils                 13.0-1-g976b40b+3 	current b2894 setup
validate_base         master-g4f5ff6b7a1 	current b2894 setup
validate_drp          master-g42ee9d6260+1 	current b2894 setup
validation_data_cfht  master-g023f152e8a+4 	current b2894 setup
validation_data_decam master-g52ac2b0d78 	current b2894 setup
wcslib                5.13.lsst1 	current b2896 b2894 b2895 setup
xpa                   2.1.15.lsst3 	current b2896 b2894 b2895

**Comment by VeraWulol** [comment]
should I do `setup -j -r . ` before `scons`? 
I tried, it seems no error is coming out now, though Im not sure if its the way to deal with it. It seems to be skipping the testCameraGeomShim.py

**Comment by jdswinbank** [comment]
Hello,

> should I do `setup -j -r .` before `scons`?

You will certainly need to set up meas_mosaic before you can successfully build and test it. If you have the rest of the stack set up, and are building meas_mosaic separately, that command should do the trick.

> I tried, it seems no error is coming out now, though Im not sure if its the way to deal with it. It seems to be skipping the testCameraGeomShim.py

However, the test should not be skipped — are you sure that's happening? It might be worth starting from a fresh copy of meas_mosaic (`git clean -dfx` can help you with this, but be aware it will delete *all* non-LSST-provided files in the meas_mosaic directory), making sure  that meas_mosaic is set up before you start.

On the other hand, I gather from your recent postings on community.lsst.org that meas_mosaic is running for you, so I suspect there's not really an issue here. If you have managed to build and test it, please close this ticket.
